### ISSUE TITLE
The container opens 4 tunnel on cloudflare

### ISSUE THREAD

**Issue by wrein** [ai-dock/comfyui#107]
why does the container open 4 tunnels on cloudflare? what are they needed for?

```
user         504  0.0  0.0 1260036 34140 ?       Sl   23:23   0:00 cloudflared tunnel --metrics localhost:28188 --url http://localhost:81
user         508  0.0  0.0 1260036 34292 ?       Sl   23:23   0:00 cloudflared tunnel --metrics localhost:21111 --url http://localhost:11
user         510  0.0  0.0 1260292 34392 ?       Sl   23:23   0:00 cloudflared tunnel --metrics localhost:28888 --url http://localhost:88
user         511  0.0  0.0 1260036 33992 ?       Sl   23:23   0:00 cloudflared tunnel --metrics localhost:28384 --url http://localhost:83
r
```

**Comment by robballantyne** [comment]
@wrein These images are designed to run in restricted cloud environments where it's difficult/impossible to generate TLS certs because of inability to open required ports.

It's configurable with `CF_QUICK_TUNNELS=false`

Please see https://github.com/ai-dock/base-image/wiki/1.0-Included-Software#cloudflared and https://github.com/ai-dock/base-image/wiki/2.0-Environment-Variables

**Comment by wrein** [comment]
Thanks Rob for the quick response, I was a little scared at first, but I figured I was missing something obvious.
