### ISSUE TITLE
How to become a tester myself for AMD/pacman platform?

### ISSUE THREAD

**Issue by petra-pannia** [ai-dock/comfyui#35]
My system info has been stated myself in reply to an old issue (i’m at work now) ☺️
```
Main system  : ASRock DeskMini X300 AMD
APU          : AMD R4750G Zen2 with 16GB UMA (graphical memories)
AMDGPU driver: 23.0.0-1 (X11)
ROCm         : 5.7.1
Python       : 3.11.6-1
Gross RAM's  : 48GB DDR4
OS           : Artix Linux amd64 with Linux kernel 6.1.70
Docker       : 24.0.7-1 / Compose 2.24.3-1
UI browser   : Brave 1.63.131-1
```
And Rob doesn’t have time to work around for AMD/pacman and my every mornings, every afternoons on every Sundays, and every entire Saturdays are free to follow such kind of stuff 🌞
So? How to become a tester and even an AMD/pacman contributre myself? 😎😉🤠😇

**Comment by robballantyne** [comment]
hey @petra-pannia you're right I've been really busy with a couple of projects so it's been difficult to track the issues on this repo although I'll be back to it very soon.

AMD has always been an issue for me because I build based on information I believe to be true about AMD but I don't have access to an AMD machine so whether it works or not has always been a bit of a mystery. I've seen docker pulls but never really had a lot of feedback.

Even telling me that it's useless and doesn't work would be a big help!

Regarding pacman, well I just don't know - The intended environment for these images is really in the data centre where it's mainly Ubuntu. I'm happy to implement fixes for other systems though but I don't have an arch setup although I can spin up an Arch VM to test things when time permits

**Comment by petra-pannia** [comment]
In instead built my own Docker at home and i’m now at work
Too few people are exclusively expecting AMD APU like myself
I expect those who download my Git projects with that Docker image to have 8GB+ UMA distributed to their APU as well ☺️
