### ISSUE TITLE
I am a noob, where do I put models and modules/plugins?

### ISSUE THREAD

**Issue by Corshi** [ai-dock/comfyui#39]
The directory structure seems different than other repos and I have no idea how to correctly use the directories of this.
Maybe a package that already contain [ltdrdata](https://github.com/ltdrdata) / [ComfyUI-Manager](https://github.com/ltdrdata/ComfyUI-Manager) ?

**Comment by hongminpark** [comment]
<img width="363" alt="image" src="https://github.com/ai-dock/comfyui/assets/21957275/1db15076-ff30-473d-b25b-3872fa6b228b">
Description is https://github.com/ai-dock/comfyui?tab=readme-ov-file#building-images here!

**Comment by robballantyne** [comment]
The storage directory only tracks models because nodes have dependencies and trying to keep them working between container teardowns is likely to break things.

The entries at `/opt/ai-dock/storage_monitor/etc/mappings.sh` determine where files should be linked to.  This is to support a future image that will contain several Stable Diffusion apps that all rely on the same models.

To install nodes you can either manually install them in `/opt/ComfyUI/custom_nodes` or you can provide a provisioning script URL on start. The default is https://raw.githubusercontent.com/ai-dock/comfyui/main/config/provisioning/default.sh but you can pass any URL that points to a bash script.

Hope this helps!

**Comment by Lady-vamp** [comment]
What about ultralytics folder? Doesn't seems to work

**Comment by robballantyne** [comment]
I'll add it in as a default this afternoon. You can also add it by adding an entry in mappings.sh if you cannot wait but I will do it today

**Comment by robballantyne** [comment]
https://github.com/ai-dock/comfyui/commit/94c7554b5cddb245236985ce472e183833565337 adds more useful mappings.

Build running at https://github.com/ai-dock/comfyui/actions/runs/8011776891
