### ISSUE TITLE
How to set Python Package Index mirror?

### ISSUE THREAD

**Issue by SoaringTiger** [ai-dock/comfyui#45]
I have changed Env variable  PIP_INSTALL="pip install --no-cache-dir -i https://mirror-site/pypi/simple".
When I manually run "micromamba -n comfyui run ${PIP_INSTALL}  xxx", the index works.

But on "docker compose up" , the mirror index doesn't seem to work, the download speed is very slow

```
supervisor-1  | Downloading diffusers-0.26.3-py3-none-any.whl (1.9 MB)
supervisor-1  |    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB _16.4 kB/s eta_ 0:00:00
```

**Comment by robballantyne** [comment]
Can you try adding `echo "$PIP_INSTALL"` in the script just to check the correct variable is being used.

I imagine it should be, but it's worth testing.

If it's not I'll check why but you can also manually override at the top of the file

**Comment by SoaringTiger** [comment]
> Can you try adding `echo "$PIP_INSTALL"` in the script just to check the correct variable is being used.
> 
> I imagine it should be, but it's worth testing.
> 
> If it's not I'll check why but you can also manually override at the top of the file

yes, echo "$PIP_INSTALL" will print :

`pip install --no-cache-dir -i https://mirror-site/pypi/simple`

**Comment by robballantyne** [comment]
I can't think of anything I could do to address this, unfortunately.

You may prefer to build the image with the nodes pre-installed to avoid having to download at runtime

**Comment by robballantyne** [comment]
Where are you setting this config?

There were quite a lot of changes made to the base before the last update, with one of the fundamental changes being that the provisioning script and most apps run in the context of 'user' rather than root. 

Could it be that the config is being activated for root so not available to the user?

What you can also try is running `source /opt/ai-dock/etc/environment.sh` at the top.
