### ISSUE TITLE
error": "[Errno 2] No such file or directory: '/workspace//ComfyUI/output//image_00001_.png'

### ISSUE THREAD

**Issue by coronell123** [ai-dock/comfyui#67]
in the basehandler for the serverless there is a small error when running it. 

    INPUT_DIR=f"{os.environ.get('WORKSPACE')}/ComfyUI/input/"
    OUTPUT_DIR=f"{os.environ.get('WORKSPACE')}/ComfyUI/output/"

This path has two // and therefore cannot be found. 
    INPUT_DIR=f"{os.environ.get('WORKSPACE')}ComfyUI/input/"
    OUTPUT_DIR=f"{os.environ.get('WORKSPACE')}ComfyUI/output/"
 Removing / from this solves this

**Comment by robballantyne** [comment]
Thank you. I'm just applying some alterations to better support alternative output formats so I'll correct this at the same time

**Comment by jgal14** [comment]
Hi @robballantyne, I'm getting the following error;

"error": "[Errno 2] No such file or directory: '/workspace//ComfyUI/output//ComfyUI_temp_pupxn_00001_.png' -> '/workspace//ComfyUI/output/test-6c8a5d8b-0438-4571-ba18-3630d0c7596d/ComfyUI_temp_pupxn_00001_.png'"
}

Is this related to the above issue? Or am I missing something else?

Thanks!

**Comment by jgal14** [comment]
Hi @robballantyne,

I've attempted to create a new image with the updated basehandler file, but I'm getting the issue referenced in https://github.com/ai-dock/comfyui/issues/56 and the build is failing so I'm a bit stuck!

**Comment by robballantyne** [comment]
The basehandler should never have referenced WORKSPACE/ComfyUI because there are occasions (no mounted volume) where it is a non existent path.

We should always point at /opt/ComfyUI because this is guaranteed to either be a directory or a symlink.

I'll push a modified version shortly which fixes the issue. If you can't wait you can replace `{os.environ.get('WORKSPACE')}` with `/opt/`

**Comment by jgal14** [comment]
> The basehandler should never have referenced WORKSPACE/ComfyUI because there are occasions (no mounted volume) where it is a non existent path.
> 
> We should always point at /opt/ComfyUI because this is guaranteed to either be a directory or a symlink.
> 
> I'll push a modified version shortly which fixes the issue. If you can't wait you can replace `{os.environ.get('WORKSPACE')}` with `/opt/`

Hi Rob,

Well put of my depth here so I'll await your fix, much appreciate the response!

Happy Friday 🍺

**Comment by jgal14** [comment]
Morning @robballantyne,

I saw a new version got pushed last night - is that the fix you mentioned?

**Comment by robballantyne** [comment]
Hi @jgal14 it's partially fixed.

I need to rebuild the base images to complete but if you rebuild this image it might be enough to solve your problem already.

The remaining issue is with input/output persistence on network volumes because `/opt/ComfyUI` is not being moved to `$WORKSPACE/ComfyUI` as I'd intended. Easy fix, but builds take a while.  Should be done today though

**Comment by jgal14** [comment]
Hi @robballantyne, ah ok great - Apologies I'm very new to the whole build process, so appreciate your explanation.

I'm actually having some problems with the docker build failing (very possibly user error, but the same thing is issue referenced here https://github.com/ai-dock/comfyui/issues/56 and you mentioned in that thread it may happen again) so I'll have to wait for the base image rebuild I think (unless there's an interim fix I can use with the Runpod Container Start Command?)
