### ISSUE TITLE
Server not ready after timeout ({timeout}s

### ISSUE THREAD

**Issue by coronell123** [ai-dock/comfyui#69]
I always get the error message from my API when building an image. I tried so many things:
changing aws s3 URL to static domain, changing my webhook, no webhook at all, all sorts of things. 
When looking into the code it becomes clear that it has something to do with this, that it cant access this URL:
    ENDPOINT_PROMPT="http://127.0.0.1:18188/prompt" 
    
I didn't find any explanation on what this does. Any suggestions

**Comment by robballantyne** [comment]
thats the local URL that ComfyUI listens on. The API is waiting for that to become available.

If it's not available you probably have a long running node installation happening or ComfyUI is crashing on start.

You can diagnose by setting an active worker and pulling the log from `/var/log/supervisor/ComfyUI.log`

I'll make the server timeout variable but you should avoid nodes that try auto-updating as they will give you long cold start times

**Comment by coronell123** [comment]
Thanks a lot. that helped

**Comment by jgal14** [comment]
Hi @robballantyne, I'm having this issue and I've cut the custom_nodes used right back.

How do I go about adjusting the server timeout value to allow more time for the nodes to populate?

**Comment by robballantyne** [comment]
> Hi @robballantyne, I'm having this issue and I've cut the custom_nodes used right back.
> 
> How do I go about adjusting the server timeout value to allow more time for the nodes to populate?

Currently hardcoded on line 223 of

**Comment by jgal14** [comment]
> > Hi @robballantyne, I'm having this issue and I've cut the custom_nodes used right back.
> > How do I go about adjusting the server timeout value to allow more time for the nodes to populate?
> 
> Currently hardcoded on line 223 of https://github.com/ai-dock/comfyui/blob/main/build/COPY_ROOT/opt/serverless/handlers/basehandler.py
> 
> I need to make that configurable just haven't got around to it yet

Cool ok got it thanks!

**Comment by jgal14** [comment]
Hey @robballantyne, 

I'm trying to get these dependencies to run on my serverless instance (I think my current approach may be causing the server time-out issues mentioned above).

pillow==10.2.0 
insightface 
onnxruntime 
onnxruntime-gpu

They aren't installed automatically by any of the custom nodes on launch, and installing on a launched pod (via the ComfuyUI manager `install PIP packages` function) first isn't transferring the dependencies over when the serverless instance is initialized.

Am I right in thinking I should add these to the `PYTHON_PACKAGES` section of the provisioning script in order to get them to install?

Help much appreciated!

**Comment by robballantyne** [comment]
No longer supporting old builds due to project direction changes.  New API wrapper will be documented soon for all serverless use cases
