### ISSUE TITLE
New release won't initialise on RunPod

### ISSUE THREAD

**Issue by danielfriis** [ai-dock/comfyui#92]
The latest release won't initialise on RunPod. It never gets past "still fetching image"

![CleanShot 2024-08-18 at 07 42 25@2x](https://github.com/user-attachments/assets/dd1f1bcd-ee60-44cf-893d-4798ea21ef25)

**Comment by robballantyne** [comment]
That's a platform issue. Probably networking issues.

While the images should run perfectly well in all cloud & local environments, I no longer use RunPod so can't help much further

**Comment by danielfriis** [comment]
Thanks for the quick response @robballantyne! Which platform do you prefer if not RunPod?

**Comment by robballantyne** [comment]
@danielfriis I've always believed `Vast.ai` is the most appropriate for my intended use case.  I created the images initially because I wanted to make it easier for people without access to a GPU (me included) to use emerging technology.

Vast is an open marketplace with many affordable cards so even on a very small budget it's possible to find something to get started with and then grow as needed.

Full disclosure - I have recently started contracting for them, so to avoid any conflict of interest I choose to stay away from similar services.  I'll always support standard `docker run` and `docker compose`  usage though, so there will never be any reason why users can't run the images however and wherever they please
